"use client"
import { useState } from "react"
import Link from "next/link"
import { ArrowRight, Search, MapPin, GraduationCap, Briefcase, BookOpen, ArrowUpRight } from "lucide-react"
import { discoveryTracks } from "@/lib/discovery"

export function DiscoveryHero() {
  const [track, setTrack] = useState("phd")
  const action = track === "trainee" ? "/trainee-programs" : track === "phd" ? "/phd-positions" : "/master-thesis"
  return <section className="discovery-hero relative overflow-hidden border-b border-border/60 px-4 pb-12 pt-12 sm:py-20">
    <div className="relative mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.35fr_0.65fr] lg:items-center">
      <div><p className="mb-5 inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.17em] text-primary"><span className="size-2 rounded-full bg-primary" />For curious minds. And what comes next.</p><h1 className="max-w-3xl text-balance text-4xl font-semibold leading-[1.08] tracking-[-0.045em] sm:text-6xl lg:text-7xl">Big ambitions.<br /><span className="text-primary">Your next chapter.</span></h1><p className="mt-6 max-w-xl text-pretty text-base leading-relaxed text-muted-foreground sm:text-lg">Find your PhD, master’s thesis, internship or graduate program. One place to explore what’s possible.</p>
      <form action={action} method="get" className="mt-8 rounded-2xl border border-border/80 bg-card p-3 shadow-[0_16px_50px_-25px_rgba(25,70,140,0.3)] sm:p-4">
        <div className="mb-3 flex gap-1 overflow-x-auto pb-1" role="group" aria-label="Choose an opportunity type">{discoveryTracks.map(item => <button key={item.key} type="button" aria-pressed={track === item.key} onClick={() => setTrack(item.key)} className={`min-h-10 shrink-0 rounded-lg px-3 text-xs font-semibold transition-colors sm:text-sm ${track === item.key ? "bg-primary/10 text-primary" : "text-muted-foreground hover:bg-muted"}`}>{item.label}</button>)}</div>
        {(track === "master" || track === "internship") && <input type="hidden" name="kind" value={track === "internship" ? "internship" : "master_thesis"} />}
        <div className="grid gap-2 sm:grid-cols-[1fr_150px_auto]"><label className="flex min-h-12 items-center gap-2 rounded-xl bg-background px-3"><Search className="size-5 shrink-0 text-primary" /><span className="sr-only">Topic, role or organization</span><input name="q" maxLength={200} placeholder="Topic, role or organization" className="w-full min-w-0 bg-transparent text-base outline-none sm:text-sm" /></label><label className="flex items-center gap-1 rounded-xl bg-background px-2"><MapPin className="size-4 shrink-0 text-muted-foreground" /><span className="sr-only">Country</span><select name="location" className="h-12 w-full min-w-0 bg-transparent text-sm"><option value="">Anywhere</option>{["Sweden", "Norway", "Finland", "Netherlands", "Germany", "Denmark", "France", "United Kingdom", "Switzerland"].map(country => <option key={country}>{country}</option>)}</select></label><button className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-primary px-5 text-sm font-semibold text-primary-foreground transition-colors hover:bg-primary/90" type="submit">Explore <ArrowRight className="size-4" /></button></div>
      </form><div className="mt-5 flex flex-wrap items-center gap-3 text-xs text-muted-foreground"><span>Popular:</span>{["Machine learning", "Engineering", "Sustainability"].map(topic => <Link key={topic} href={`/phd-positions?q=${encodeURIComponent(topic)}`} className="underline decoration-border underline-offset-4 hover:text-primary">{topic}</Link>)}</div></div>
      <div className="relative hidden py-8 lg:block"><div aria-hidden="true" className="absolute -inset-6 rounded-full border border-primary/10" /><div aria-hidden="true" className="absolute inset-4 rounded-full border border-primary/10" /><div className="relative space-y-4">{[{icon:GraduationCap,title:"Make your next discovery",label:"PhD & research",href:"/phd-positions"},{icon:BookOpen,title:"Put your ideas to work",label:"Theses & internships",href:"/master-thesis"},{icon:Briefcase,title:"Build a career with purpose",label:"Graduate programs",href:"/trainee-programs"}].map((item,index) => <Link key={item.href} href={item.href} className={`opportunity-card flex items-center gap-4 rounded-2xl border border-border/80 bg-card/95 p-5 shadow-sm ${index === 1 ? "-translate-x-5" : ""}`}><span className="flex size-12 shrink-0 items-center justify-center rounded-xl bg-primary/8 text-primary"><item.icon className="size-6" /></span><div><p className="text-xs text-muted-foreground">{item.label}</p><p className="mt-1 text-sm font-semibold">{item.title}</p></div><ArrowUpRight className="ml-auto size-4 shrink-0 text-primary" /></Link>)}</div></div>
    </div>
  </section>
}
