import type { PhdImportSourceDefinition } from "./types"

const norwegianUniversities = [
  {
    name: "University of Oslo",
    aliases: ["University of Oslo", "Universitetet i Oslo", "UiO"],
    defaultLocation: "Oslo, Norway",
  },
  {
    name: "University of Bergen",
    aliases: ["University of Bergen", "Universitetet i Bergen", "UiB"],
    defaultLocation: "Bergen, Norway",
  },
  {
    name: "NTNU",
    aliases: [
      "NTNU",
      "Norwegian University of Science and Technology",
      "Norges teknisk-naturvitenskapelige universitet",
    ],
    defaultLocation: "Trondheim, Norway",
  },
  {
    name: "UiT The Arctic University of Norway",
    aliases: ["UiT The Arctic University of Norway", "UiT Norges arktiske universitet"],
    defaultLocation: "Tromso, Norway",
  },
  {
    name: "University of Stavanger",
    aliases: ["University of Stavanger", "Universitetet i Stavanger", "UiS"],
    defaultLocation: "Stavanger, Norway",
  },
  {
    name: "Norwegian University of Life Sciences",
    aliases: ["Norwegian University of Life Sciences", "Norges miljo- og biovitenskapelige universitet", "NMBU"],
    defaultLocation: "As, Norway",
  },
  {
    name: "OsloMet",
    aliases: ["OsloMet", "Oslo Metropolitan University"],
    defaultLocation: "Oslo, Norway",
  },
  {
    name: "University of Agder",
    aliases: ["University of Agder", "Universitetet i Agder", "UiA"],
    defaultLocation: "Kristiansand, Norway",
  },
  {
    name: "Nord University",
    aliases: ["Nord University", "Nord universitet"],
    defaultLocation: "Bodo, Norway",
  },
]

const dutchUniversities = [
  {
    name: "University of Amsterdam",
    aliases: ["University of Amsterdam", "Universiteit van Amsterdam", "UvA"],
    defaultLocation: "Amsterdam, Netherlands",
  },
  {
    name: "Vrije Universiteit Amsterdam",
    aliases: ["Vrije Universiteit Amsterdam", "VU Amsterdam"],
    defaultLocation: "Amsterdam, Netherlands",
  },
  {
    name: "Utrecht University",
    aliases: ["Utrecht University", "Universiteit Utrecht"],
    defaultLocation: "Utrecht, Netherlands",
  },
  {
    name: "Delft University of Technology",
    aliases: ["Delft University of Technology", "TU Delft"],
    defaultLocation: "Delft, Netherlands",
  },
  {
    name: "Erasmus University Rotterdam",
    aliases: ["Erasmus University Rotterdam", "Erasmus Universiteit Rotterdam", "EUR"],
    defaultLocation: "Rotterdam, Netherlands",
  },
  {
    name: "Leiden University",
    aliases: ["Leiden University", "Universiteit Leiden"],
    defaultLocation: "Leiden, Netherlands",
  },
  {
    name: "University of Groningen",
    aliases: ["University of Groningen", "Rijksuniversiteit Groningen", "RUG"],
    defaultLocation: "Groningen, Netherlands",
  },
  {
    name: "Radboud University",
    aliases: ["Radboud University", "Radboud Universiteit"],
    defaultLocation: "Nijmegen, Netherlands",
  },
  {
    name: "Wageningen University & Research",
    aliases: ["Wageningen University & Research", "Wageningen University and Research", "WUR"],
    defaultLocation: "Wageningen, Netherlands",
  },
  {
    name: "Eindhoven University of Technology",
    aliases: ["Eindhoven University of Technology", "TU/e"],
    defaultLocation: "Eindhoven, Netherlands",
  },
  {
    name: "University of Twente",
    aliases: ["University of Twente", "Universiteit Twente"],
    defaultLocation: "Enschede, Netherlands",
  },
  {
    name: "Maastricht University",
    aliases: ["Maastricht University", "Universiteit Maastricht"],
    defaultLocation: "Maastricht, Netherlands",
  },
  {
    name: "Tilburg University",
    aliases: ["Tilburg University", "Universiteit van Tilburg"],
    defaultLocation: "Tilburg, Netherlands",
  },
]

export const PHD_IMPORT_SOURCES: PhdImportSourceDefinition[] = [
  {
    id: "uppsala-university",
    name: "Uppsala University vacancies",
    organization: "Uppsala University",
    country: "Sweden",
    defaultLocation: "Uppsala, Sweden",
    sourceUrl: "https://www.uu.se/en/about-uu/join-us/jobs-and-vacancies",
    publicUrl: "https://www.uu.se/en/about-uu/join-us/jobs-and-vacancies",
    platform: "html",
    allowedHosts: ["www.uu.se", "uu.varbi.com"],
  },
  {
    id: "lund-university",
    name: "Lund University vacancies",
    organization: "Lund University",
    country: "Sweden",
    defaultLocation: "Lund, Sweden",
    sourceUrl: "https://www.lunduniversity.lu.se/vacancies",
    publicUrl: "https://www.lunduniversity.lu.se/vacancies",
    platform: "html",
    allowedHosts: ["www.lunduniversity.lu.se", "lu.varbi.com"],
  },
  {
    id: "university-of-gothenburg",
    name: "University of Gothenburg vacancies",
    organization: "University of Gothenburg",
    country: "Sweden",
    defaultLocation: "Gothenburg, Sweden",
    sourceUrl: "https://www.gu.se/en/work-at-the-university-of-gothenburg/vacancies",
    publicUrl: "https://www.gu.se/en/work-at-the-university-of-gothenburg/vacancies",
    platform: "html",
    allowedHosts: ["www.gu.se", "web103.reachmee.com"],
  },
  {
    id: "stockholm-university",
    name: "Stockholm University vacancies",
    organization: "Stockholm University",
    country: "Sweden",
    defaultLocation: "Stockholm, Sweden",
    sourceUrl: "https://su.varbi.com/en/",
    publicUrl: "https://www.su.se/english/about-the-university/work-at-su/available-jobs",
    platform: "html",
    allowedHosts: ["su.varbi.com"],
  },
  {
    id: "kth",
    name: "KTH vacancies",
    organization: "KTH Royal Institute of Technology",
    country: "Sweden",
    defaultLocation: "Stockholm, Sweden",
    sourceUrl: "https://kth.varbi.com/en/",
    publicUrl: "https://kth.varbi.com/en/",
    platform: "html",
    allowedHosts: ["kth.varbi.com"],
  },
  {
    id: "chalmers",
    name: "Chalmers vacancies",
    organization: "Chalmers University of Technology",
    country: "Sweden",
    defaultLocation: "Gothenburg, Sweden",
    sourceUrl: "https://web103.reachmee.com/ext/I003/304/main?site=5&validator=a72aeedd63ec10de71e46f8d91d0d57c&lang=UK",
    publicUrl: "https://www.chalmers.se/en/about-chalmers/work-with-us/vacancies/",
    platform: "html",
    allowedHosts: ["web103.reachmee.com"],
  },
  {
    id: "linkoping-university",
    name: "Linkoping University vacancies",
    organization: "Linkoping University",
    country: "Sweden",
    defaultLocation: "Linkoping, Sweden",
    sourceUrl: "https://liu.se/rss/liu-jobs-en.rss",
    publicUrl: "https://liu.se/en/work-at-liu/vacancies",
    platform: "feed",
    allowedHosts: ["liu.se", "site106.reachmee.com", "web103.reachmee.com"],
  },
  {
    id: "karolinska-institutet",
    name: "Karolinska Institutet vacancies",
    organization: "Karolinska Institutet",
    country: "Sweden",
    defaultLocation: "Stockholm, Sweden",
    sourceUrl: "https://ki.se/en/vacancies",
    publicUrl: "https://ki.se/en/vacancies",
    platform: "html",
    allowedHosts: ["ki.se", "www.ki.se", "ki.varbi.com", "kidoktorand.varbi.com"],
  },
  {
    id: "umea-university",
    name: "Umea University vacancies",
    organization: "Umea University",
    country: "Sweden",
    defaultLocation: "Umea, Sweden",
    sourceUrl: "https://umu.varbi.com/en/",
    publicUrl: "https://umu.varbi.com/en/",
    platform: "html",
    allowedHosts: ["umu.varbi.com"],
  },
  {
    id: "lulea-university-of-technology",
    name: "Lulea University of Technology vacancies",
    organization: "Lulea University of Technology",
    country: "Sweden",
    defaultLocation: "Lulea, Sweden",
    sourceUrl: "https://web103.reachmee.com/ext/I003/583/main?site=6&validator=e4575239eb8c0828707e2b716f86c5f8&lang=UK",
    publicUrl: "https://www.ltu.se/en/about-the-university/work-with-us/job-vacancies",
    platform: "html",
    allowedHosts: ["web103.reachmee.com"],
  },
  {
    id: "orebro-university",
    name: "Orebro University vacancies",
    organization: "Orebro University",
    country: "Sweden",
    defaultLocation: "Orebro, Sweden",
    sourceUrl: "https://www.oru.se/english/career/available-positions/",
    publicUrl: "https://www.oru.se/english/career/available-positions/",
    platform: "html",
    allowedHosts: ["www.oru.se"],
  },
  {
    id: "malmo-university",
    name: "Malmo University vacancies",
    organization: "Malmo University",
    country: "Sweden",
    defaultLocation: "Malmo, Sweden",
    sourceUrl: "https://mau.se/en/about-us/job-offers/current-vacancies/",
    publicUrl: "https://mau.se/en/about-us/job-offers/current-vacancies/",
    platform: "html",
    allowedHosts: ["mau.se", "www.mau.se", "web103.reachmee.com"],
  },
  {
    id: "linnaeus-university",
    name: "Linnaeus University vacancies",
    organization: "Linnaeus University",
    country: "Sweden",
    defaultLocation: "Vaxjo or Kalmar, Sweden",
    sourceUrl: "https://web103.reachmee.com/ext/I009/613/main?site=7&validator=696d86b542bf9f7d3a3da97c96c9eb28&lang=UK",
    publicUrl: "https://www.lnu.se/en/meet-linnaeus-university/work-with-us/vacancies-page/",
    platform: "html",
    allowedHosts: ["web103.reachmee.com"],
  },
  {
    id: "karlstad-university",
    name: "Karlstad University vacancies",
    organization: "Karlstad University",
    country: "Sweden",
    defaultLocation: "Karlstad, Sweden",
    sourceUrl: "https://kau.varbi.com/en/",
    publicUrl: "https://www.kau.se/en/work-us/work/vacancies",
    platform: "html",
    allowedHosts: ["kau.varbi.com"],
  },
  {
    id: "malardalen-university",
    name: "Malardalen University vacancies",
    organization: "Malardalen University",
    country: "Sweden",
    defaultLocation: "Vasteras or Eskilstuna, Sweden",
    sourceUrl: "https://www.mdu.se/en/malardalen-university/about-mdu/work-with-us/job-opportunities",
    publicUrl: "https://www.mdu.se/en/malardalen-university/about-mdu/work-with-us/job-opportunities",
    platform: "html",
    allowedHosts: ["www.mdu.se", "web103.reachmee.com"],
  },
  {
    id: "slu",
    name: "SLU vacancies",
    organization: "Swedish University of Agricultural Sciences",
    country: "Sweden",
    defaultLocation: "Sweden",
    sourceUrl: "https://www.slu.se/sitemap.xml",
    publicUrl: "https://www.slu.se/en/about-slu/work-at-slu/jobs-and-vacancies/",
    platform: "sitemap",
    allowedHosts: ["www.slu.se"],
    detailUrlPrefix: "https://www.slu.se/en/about-slu/work-at-slu/jobs-and-vacancies/",
  },
  {
    id: "jonkoping-university",
    name: "Jonkoping University vacancies",
    organization: "Jonkoping University",
    country: "Sweden",
    defaultLocation: "Jonkoping, Sweden",
    sourceUrl: "https://ju.se/en/about-us/work-at-jonkoping-university/job-vacancies.html",
    publicUrl: "https://ju.se/en/about-us/work-at-jonkoping-university/job-vacancies.html",
    platform: "html",
    allowedHosts: ["ju.se", "www.ju.se", "ju.varbi.com"],
  },
  {
    id: "norwegian-universities-jobbnorge",
    name: "Norwegian university vacancies via Jobbnorge",
    organization: "Norwegian universities",
    country: "Norway",
    defaultLocation: "Norway",
    sourceUrl: "https://publicapi.jobbnorge.no/v3/jobs?OrderBy=Published&Period=All&language=1",
    publicUrl: "https://www.jobbnorge.no/search/en?OrderBy=Published&Period=All",
    platform: "json",
    adapter: "jobbnorge-api",
    allowedHosts: ["publicapi.jobbnorge.no", "www.jobbnorge.no", "jobbnorge.no"],
    jobUrlPattern: /\/(?:ledige-stillinger\/stilling|en\/available-jobs\/job)\/\d+/i,
    maxJobs: 180,
    maxListingBytes: 8 * 1024 * 1024,
    organizations: norwegianUniversities,
  },
  {
    id: "netherlands-academictransfer",
    name: "Dutch university PhD vacancies via AcademicTransfer",
    organization: "Dutch universities",
    country: "Netherlands",
    defaultLocation: "Netherlands",
    sourceUrl: "https://www.academictransfer.com/en/job-type/phd/",
    publicUrl: "https://www.academictransfer.com/en/job-type/phd/",
    platform: "json",
    adapter: "academictransfer-api",
    allowedHosts: ["www.academictransfer.com", "academictransfer.com", "api.academictransfer.com"],
    jobUrlPattern: /\/en\/jobs\/\d+\//i,
    maxJobs: 300,
    maxListingBytes: 12 * 1024 * 1024,
    organizations: dutchUniversities,
  },
  {
    id: "university-of-helsinki",
    name: "University of Helsinki vacancies",
    organization: "University of Helsinki",
    country: "Finland",
    defaultLocation: "Helsinki, Finland",
    sourceUrl: "https://jobs.helsinki.fi/search/",
    publicUrl: "https://jobs.helsinki.fi/",
    platform: "html",
    allowedHosts: ["jobs.helsinki.fi"],
    jobUrlPattern: /\/job\/[^?#]+/i,
    maxJobs: 80,
  },
  {
    id: "aalto-university",
    name: "Aalto University vacancies",
    organization: "Aalto University",
    country: "Finland",
    defaultLocation: "Espoo, Finland",
    sourceUrl: "https://www.aalto.fi/en/open-positions",
    publicUrl: "https://www.aalto.fi/en/open-positions",
    platform: "html",
    allowedHosts: ["www.aalto.fi", "aalto.fi"],
    jobUrlPattern: /\/en\/open-positions\/[^/?#]+\/?$/i,
    listingPageCount: 5,
    listingPageParameter: "page",
    listingPageStart: 1,
    maxJobs: 80,
  },
  {
    id: "tampere-university",
    name: "Tampere University vacancies",
    organization: "Tampere University",
    country: "Finland",
    defaultLocation: "Tampere, Finland",
    sourceUrl: "https://www.tuni.fi/en/tau/work-with-us/open-positions?navref=search--list",
    publicUrl: "https://www.tuni.fi/en/tau/work-with-us/open-positions",
    platform: "html",
    allowedHosts: ["www.tuni.fi", "tuni.fi", "tuni.rekrytointi.com"],
    jobUrlPattern: /\/paikat\/.*[?&]jid=\d+/i,
    maxJobs: 80,
  },
  {
    id: "university-of-turku",
    name: "University of Turku vacancies",
    organization: "University of Turku",
    country: "Finland",
    defaultLocation: "Turku, Finland",
    sourceUrl: "https://ats.talentadore.com/positions/3VMfJS4/json?v=2&display_language=en&tags=&notTags=&businessUnits=&notBusinessUnits=&display_description=job_ad&categories=tags_and_extras",
    publicUrl: "https://www.utu.fi/en/university/come-work-with-us/open-vacancies",
    platform: "json",
    adapter: "talentadore-json",
    allowedHosts: ["ats.talentadore.com"],
    jobUrlPattern: /\/apply\/[^?#]+\/[a-z0-9_-]+\/?$/i,
    maxJobs: 80,
    maxListingBytes: 10 * 1024 * 1024,
  },
  {
    id: "university-of-jyvaskyla",
    name: "University of Jyvaskyla vacancies",
    organization: "University of Jyvaskyla",
    country: "Finland",
    defaultLocation: "Jyvaskyla, Finland",
    sourceUrl: "https://www.jyu.fi/en/about-us/work-with-us/current-vacancies-at-the-university-of-jyvaskyla",
    publicUrl: "https://www.jyu.fi/en/about-us/work-with-us/current-vacancies-at-the-university-of-jyvaskyla",
    platform: "html",
    allowedHosts: ["www.jyu.fi", "jyu.fi", "ats.talentadore.com"],
    jobUrlPattern: /\/apply\/[^?#]+\/[a-z0-9_-]+\/?$/i,
    maxJobs: 80,
  },
  {
    id: "university-of-oulu",
    name: "University of Oulu vacancies",
    organization: "University of Oulu",
    country: "Finland",
    defaultLocation: "Oulu, Finland",
    sourceUrl: "https://oulunyliopisto.varbi.com/en/",
    publicUrl: "https://oulunyliopisto.varbi.com/en/",
    platform: "html",
    allowedHosts: ["oulunyliopisto.varbi.com"],
    maxJobs: 80,
  },
  {
    id: "university-of-eastern-finland",
    name: "University of Eastern Finland vacancies",
    organization: "University of Eastern Finland",
    country: "Finland",
    defaultLocation: "Joensuu or Kuopio, Finland",
    sourceUrl: "https://www.uef.fi/en/open-positions",
    publicUrl: "https://www.uef.fi/en/open-positions",
    platform: "html",
    allowedHosts: ["www.uef.fi", "uef.fi", "uef.varbi.com"],
    maxJobs: 80,
  },
  {
    id: "lut-university",
    name: "LUT University vacancies",
    organization: "LUT University",
    country: "Finland",
    defaultLocation: "Lappeenranta or Lahti, Finland",
    sourceUrl: "https://lut.rekrytointi.com/paikat/index.php?fid=4&lang=en&list=1&o=A_LOJ",
    publicUrl: "https://lut.rekrytointi.com/paikat/index.php?fid=4&lang=en&list=1&o=A_LOJ",
    platform: "html",
    allowedHosts: ["lut.rekrytointi.com"],
    jobUrlPattern: /\/paikat\/index\.php.*[?&]jid=\d+/i,
    maxJobs: 80,
  },
  {
    id: "abo-akademi-university",
    name: "Abo Akademi University vacancies",
    organization: "Abo Akademi University",
    country: "Finland",
    defaultLocation: "Turku or Vaasa, Finland",
    sourceUrl: "https://abo.rekrytointi.com/paikat/index.php?key=&lang=en&list=1&o=A_LOJ",
    publicUrl: "https://abo.rekrytointi.com/paikat/index.php?key=&lang=en&list=1&o=A_LOJ",
    platform: "html",
    allowedHosts: ["abo.rekrytointi.com"],
    jobUrlPattern: /\/paikat\/index\.php.*[?&]jid=\d+/i,
    maxJobs: 80,
  },
]

const sourcesById = new Map(PHD_IMPORT_SOURCES.map((source) => [source.id, source]))

export function getPhdImportSource(sourceId: string) {
  return sourcesById.get(sourceId)
}

export function getPhdImportSources(sourceIds?: string[]) {
  if (!sourceIds?.length) return PHD_IMPORT_SOURCES
  const requested = new Set(sourceIds)
  return PHD_IMPORT_SOURCES.filter((source) => requested.has(source.id))
}
