import type { PhdImportSourceDefinition } from "./types"

export const PHD_IMPORT_SOURCES: PhdImportSourceDefinition[] = [
  {
    id: "uppsala-university",
    name: "Uppsala University vacancies",
    organization: "Uppsala University",
    country: "Sweden",
    defaultLocation: "Uppsala, Sweden",
    sourceUrl: "https://www.uu.se/en/about-uu/join-us/jobs-and-vacancies",
    publicUrl: "https://www.uu.se/en/about-uu/join-us/jobs-and-vacancies",
    platform: "html",
    allowedHosts: ["www.uu.se", "uu.varbi.com"],
  },
  {
    id: "lund-university",
    name: "Lund University vacancies",
    organization: "Lund University",
    country: "Sweden",
    defaultLocation: "Lund, Sweden",
    sourceUrl: "https://www.lunduniversity.lu.se/vacancies",
    publicUrl: "https://www.lunduniversity.lu.se/vacancies",
    platform: "html",
    allowedHosts: ["www.lunduniversity.lu.se", "lu.varbi.com"],
  },
  {
    id: "university-of-gothenburg",
    name: "University of Gothenburg vacancies",
    organization: "University of Gothenburg",
    country: "Sweden",
    defaultLocation: "Gothenburg, Sweden",
    sourceUrl: "https://www.gu.se/en/work-at-the-university-of-gothenburg/vacancies",
    publicUrl: "https://www.gu.se/en/work-at-the-university-of-gothenburg/vacancies",
    platform: "html",
    allowedHosts: ["www.gu.se", "web103.reachmee.com"],
  },
  {
    id: "stockholm-university",
    name: "Stockholm University vacancies",
    organization: "Stockholm University",
    country: "Sweden",
    defaultLocation: "Stockholm, Sweden",
    sourceUrl: "https://su.varbi.com/en/",
    publicUrl: "https://www.su.se/english/about-the-university/work-at-su/available-jobs",
    platform: "html",
    allowedHosts: ["su.varbi.com"],
  },
  {
    id: "kth",
    name: "KTH vacancies",
    organization: "KTH Royal Institute of Technology",
    country: "Sweden",
    defaultLocation: "Stockholm, Sweden",
    sourceUrl: "https://kth.varbi.com/en/",
    publicUrl: "https://kth.varbi.com/en/",
    platform: "html",
    allowedHosts: ["kth.varbi.com"],
  },
  {
    id: "chalmers",
    name: "Chalmers vacancies",
    organization: "Chalmers University of Technology",
    country: "Sweden",
    defaultLocation: "Gothenburg, Sweden",
    sourceUrl: "https://web103.reachmee.com/ext/I003/304/main?site=5&validator=a72aeedd63ec10de71e46f8d91d0d57c&lang=UK",
    publicUrl: "https://www.chalmers.se/en/about-chalmers/work-with-us/vacancies/",
    platform: "html",
    allowedHosts: ["web103.reachmee.com"],
  },
  {
    id: "linkoping-university",
    name: "Linkoping University vacancies",
    organization: "Linkoping University",
    country: "Sweden",
    defaultLocation: "Linkoping, Sweden",
    sourceUrl: "https://liu.se/rss/liu-jobs-en.rss",
    publicUrl: "https://liu.se/en/work-at-liu/vacancies",
    platform: "feed",
    allowedHosts: ["liu.se", "site106.reachmee.com", "web103.reachmee.com"],
  },
  {
    id: "karolinska-institutet",
    name: "Karolinska Institutet vacancies",
    organization: "Karolinska Institutet",
    country: "Sweden",
    defaultLocation: "Stockholm, Sweden",
    sourceUrl: "https://ki.se/en/vacancies",
    publicUrl: "https://ki.se/en/vacancies",
    platform: "html",
    allowedHosts: ["ki.se", "www.ki.se", "ki.varbi.com", "kidoktorand.varbi.com"],
  },
  {
    id: "umea-university",
    name: "Umea University vacancies",
    organization: "Umea University",
    country: "Sweden",
    defaultLocation: "Umea, Sweden",
    sourceUrl: "https://umu.varbi.com/en/",
    publicUrl: "https://umu.varbi.com/en/",
    platform: "html",
    allowedHosts: ["umu.varbi.com"],
  },
  {
    id: "lulea-university-of-technology",
    name: "Lulea University of Technology vacancies",
    organization: "Lulea University of Technology",
    country: "Sweden",
    defaultLocation: "Lulea, Sweden",
    sourceUrl: "https://web103.reachmee.com/ext/I003/583/main?site=6&validator=e4575239eb8c0828707e2b716f86c5f8&lang=UK",
    publicUrl: "https://www.ltu.se/en/about-the-university/work-with-us/job-vacancies",
    platform: "html",
    allowedHosts: ["web103.reachmee.com"],
  },
  {
    id: "orebro-university",
    name: "Orebro University vacancies",
    organization: "Orebro University",
    country: "Sweden",
    defaultLocation: "Orebro, Sweden",
    sourceUrl: "https://www.oru.se/english/career/available-positions/",
    publicUrl: "https://www.oru.se/english/career/available-positions/",
    platform: "html",
    allowedHosts: ["www.oru.se"],
  },
  {
    id: "malmo-university",
    name: "Malmo University vacancies",
    organization: "Malmo University",
    country: "Sweden",
    defaultLocation: "Malmo, Sweden",
    sourceUrl: "https://mau.se/en/about-us/job-offers/current-vacancies/",
    publicUrl: "https://mau.se/en/about-us/job-offers/current-vacancies/",
    platform: "html",
    allowedHosts: ["mau.se", "www.mau.se", "web103.reachmee.com"],
  },
  {
    id: "linnaeus-university",
    name: "Linnaeus University vacancies",
    organization: "Linnaeus University",
    country: "Sweden",
    defaultLocation: "Vaxjo or Kalmar, Sweden",
    sourceUrl: "https://web103.reachmee.com/ext/I009/613/main?site=7&validator=696d86b542bf9f7d3a3da97c96c9eb28&lang=UK",
    publicUrl: "https://www.lnu.se/en/meet-linnaeus-university/work-with-us/vacancies-page/",
    platform: "html",
    allowedHosts: ["web103.reachmee.com"],
  },
  {
    id: "karlstad-university",
    name: "Karlstad University vacancies",
    organization: "Karlstad University",
    country: "Sweden",
    defaultLocation: "Karlstad, Sweden",
    sourceUrl: "https://kau.varbi.com/en/",
    publicUrl: "https://www.kau.se/en/work-us/work/vacancies",
    platform: "html",
    allowedHosts: ["kau.varbi.com"],
  },
  {
    id: "malardalen-university",
    name: "Malardalen University vacancies",
    organization: "Malardalen University",
    country: "Sweden",
    defaultLocation: "Vasteras or Eskilstuna, Sweden",
    sourceUrl: "https://www.mdu.se/en/malardalen-university/about-mdu/work-with-us/job-opportunities",
    publicUrl: "https://www.mdu.se/en/malardalen-university/about-mdu/work-with-us/job-opportunities",
    platform: "html",
    allowedHosts: ["www.mdu.se", "web103.reachmee.com"],
  },
  {
    id: "slu",
    name: "SLU vacancies",
    organization: "Swedish University of Agricultural Sciences",
    country: "Sweden",
    defaultLocation: "Sweden",
    sourceUrl: "https://www.slu.se/sitemap.xml",
    publicUrl: "https://www.slu.se/en/about-slu/work-at-slu/jobs-and-vacancies/",
    platform: "sitemap",
    allowedHosts: ["www.slu.se"],
    detailUrlPrefix: "https://www.slu.se/en/about-slu/work-at-slu/jobs-and-vacancies/",
  },
  {
    id: "jonkoping-university",
    name: "Jonkoping University vacancies",
    organization: "Jonkoping University",
    country: "Sweden",
    defaultLocation: "Jonkoping, Sweden",
    sourceUrl: "https://ju.se/en/about-us/work-at-jonkoping-university/job-vacancies.html",
    publicUrl: "https://ju.se/en/about-us/work-at-jonkoping-university/job-vacancies.html",
    platform: "html",
    allowedHosts: ["ju.se", "www.ju.se", "ju.varbi.com"],
  },
]

const sourcesById = new Map(PHD_IMPORT_SOURCES.map((source) => [source.id, source]))

export function getPhdImportSource(sourceId: string) {
  return sourcesById.get(sourceId)
}

export function getPhdImportSources(sourceIds?: string[]) {
  if (!sourceIds?.length) return PHD_IMPORT_SOURCES
  const requested = new Set(sourceIds)
  return PHD_IMPORT_SOURCES.filter((source) => requested.has(source.id))
}
