import type { TraineeImportSourceDefinition } from "./types"

export const TRAINEE_IMPORT_SOURCES: TraineeImportSourceDefinition[] = [
  {
    id: "traineeguiden-sweden",
    name: "TraineeGuiden Sweden",
    organization: "TraineeGuiden",
    country: "Sweden",
    defaultLocation: "Sweden",
    sourceUrl: "https://www.traineeguiden.se/wp-json/wp/v2/trainee-program?per_page=100&page=1",
    publicUrl: "https://www.traineeguiden.se/",
    platform: "wordpress",
    adapter: "traineeguiden-wordpress",
    allowedHosts: ["www.traineeguiden.se", "traineeguiden.se"],
    maxJobs: 100,
    maxListingBytes: 8 * 1024 * 1024,
    scannable: true,
  },
  {
    id: "graduateships",
    name: "Graduateships graduate programmes",
    organization: "Graduateships",
    country: "Europe",
    defaultLocation: "Europe",
    sourceUrl: "https://graduateships.com/job-location/eu/",
    publicUrl: "https://graduateships.com/",
    platform: "html",
    adapter: "graduateships-ajax",
    allowedHosts: ["graduateships.com", "www.graduateships.com"],
    maxJobs: 60,
    maxListingBytes: 8 * 1024 * 1024,
    scannable: true,
  },
  {
    id: "targetjobs",
    name: "TargetJobs graduate schemes",
    organization: "TargetJobs",
    country: "United Kingdom",
    defaultLocation: "United Kingdom",
    sourceUrl: "https://targetjobs.co.uk/s/jobs/graduate-scheme",
    publicUrl: "https://targetjobs.co.uk/",
    platform: "html",
    adapter: "targetjobs-html",
    allowedHosts: ["targetjobs.co.uk", "www.targetjobs.co.uk"],
    listingPageCount: 2,
    maxJobs: 50,
    maxListingBytes: 3 * 1024 * 1024,
    scannable: true,
  },
  {
    id: "higherin",
    name: "Higherin graduate schemes",
    organization: "Higherin",
    country: "United Kingdom",
    defaultLocation: "United Kingdom",
    sourceUrl: "https://higherin.com/search-jobs/graduate-scheme",
    publicUrl: "https://higherin.com/search-jobs/graduate-scheme",
    platform: "json",
    adapter: "higherin-state",
    allowedHosts: ["higherin.com", "www.higherin.com"],
    listingPageCount: 3,
    maxJobs: 75,
    maxListingBytes: 3 * 1024 * 1024,
    scannable: true,
  },
  {
    id: "milkround",
    name: "Milkround graduate schemes",
    organization: "Milkround",
    country: "United Kingdom",
    defaultLocation: "United Kingdom",
    sourceUrl: "https://www.milkround.com/jobs/graduate-scheme",
    publicUrl: "https://www.milkround.com/",
    platform: "html",
    adapter: "milkround-html",
    allowedHosts: ["www.milkround.com", "milkround.com", "www.totaljobs.com", "totaljobs.com"],
    maxJobs: 25,
    maxListingBytes: 3 * 1024 * 1024,
    crawlDelayMs: 1_000,
    scannable: true,
  },
  {
    id: "graduate-programmes-directory",
    name: "Graduate Programmes directory",
    organization: "Graduate Programmes",
    country: "International",
    defaultLocation: "International",
    sourceUrl: "https://www.graduate-programmes.com/en/graduate-programmes-list",
    publicUrl: "https://www.graduate-programmes.com/en/graduate-programmes-list",
    platform: "html",
    allowedHosts: ["www.graduate-programmes.com", "graduate-programmes.com"],
    scannable: false,
    accessNote: "This is an evergreen employer directory without a reliable current-vacancy feed or application deadlines. Connect a licensed feed before enabling imports.",
  },
  {
    id: "gradcracker",
    name: "Gradcracker",
    organization: "Gradcracker",
    country: "United Kingdom",
    defaultLocation: "United Kingdom",
    sourceUrl: "https://www.gradcracker.com/",
    publicUrl: "https://www.gradcracker.com/",
    platform: "html",
    allowedHosts: ["www.gradcracker.com", "gradcracker.com"],
    scannable: false,
    accessNote: "Gradcracker's published terms prohibit scraping. Written permission or an authorized feed is required.",
  },
  {
    id: "eures",
    name: "EURES job mobility portal",
    organization: "European Labour Authority",
    country: "European Union",
    defaultLocation: "European Union",
    sourceUrl: "https://europa.eu/eures/portal/",
    publicUrl: "https://europa.eu/eures/portal/",
    platform: "html",
    allowedHosts: ["europa.eu", "eures.europa.eu"],
    scannable: false,
    accessNote: "EURES does not permit screen scraping or republication. Its extraction API is reserved for recognized EURES partners.",
  },
]

export function getTraineeImportSource(sourceId: string) {
  return TRAINEE_IMPORT_SOURCES.find((source) => source.id === sourceId)
}

export function getTraineeImportSources(sourceIds?: string[]) {
  if (!sourceIds?.length) return TRAINEE_IMPORT_SOURCES.filter((source) => source.scannable)
  const selected = new Set(sourceIds)
  return TRAINEE_IMPORT_SOURCES.filter((source) => selected.has(source.id) && source.scannable)
}
