import Link from "next/link"
import { PublicLayout } from "@/components/layout/public-layout"

export default function PrivacyPolicyPage() {
  const sections = [
    ["Data and purposes", "We use your name, email, role, authentication details, optional profile information, saved opportunities, and application markers to provide your requested account services (Article 6(1)(b), contract). Optional profile fields are not required to register. Listings, blogs, testimonials, and comments are reviewed for publication at your request. Published content and author names may be seen by anyone, including search engines. Avoid submitting sensitive information or information about others without permission."],
    ["Security and correspondence", "Hosting and authentication providers process technical information such as IP addresses and request logs to deliver and secure the service. Security and abuse prevention rely on legitimate interests in protecting the platform (Article 6(1)(f)), subject to a balancing assessment. Support correspondence is used to respond to your request; legal rights requests are handled to comply with our obligations (Article 6(1)(c)). The contact form opens your email application; it does not itself submit a message to our database."],
    ["Providers and international transfers", "We use Supabase for authentication, database, and uploaded-file storage, and Vercel for hosting. If you choose Google sign-in, we receive identity details such as name, email, and profile image from Google. Opportunity listings may come from public university and employer websites, with source links. External application sites operate under their own privacy notices. Provider processing locations, subprocessors, and transfers outside the EEA must be confirmed before production launch. Transfers require an applicable adequacy decision or appropriate safeguards, such as standard contractual clauses and any necessary supplementary measures. Contact us for details and copies of applicable safeguards."],
    ["Cookies, browser storage, and analytics", "Optional website analytics are disabled. Authentication cookies maintain your session; temporary registration cookies expire after ten minutes and the legacy administrator session after one day. Browser storage supports requested features such as opportunity comparison and interface preferences and can be cleared in browser settings. Clearing authentication storage signs you out. Provider-managed session lifetimes depend on authentication configuration. Images may be served through Supabase, Google, or Unsplash. We do not use advertising trackers."],
    ["Retention and deletion", "Account records are used for the duration of the account. Content may remain published until removed, including author names stored separately from the account. Deletion requests must include review of content, uploaded files, caches, and provider copies. Data may be retained where required by law or necessary for legal claims, with access restricted. Production retention periods for inactive accounts, correspondence, logs, backups, and cached images are still being finalized and must be documented before launch. Contact us for applicable periods. Removal from backups or third-party search caches is not necessarily immediate."],
    ["Your rights", "You may request access, correction, erasure, restriction, and, where applicable, portability. You may object to processing based on legitimate interests. Where processing relies on consent, you may withdraw it without affecting earlier lawful processing. Requests normally receive a response within one month; for complex or numerous requests, up to two further months are allowed if we explain the extension within the first month. We may request proportionate identity verification and will explain any lawful refusal. Account registration is not consent to marketing."],
    ["Recommendations and complaints", "The opportunity assistant uses listing information and filters to help discovery; it does not make admission or employment decisions. You may complain to a supervisory authority, including in the country where you live, work, or where a suspected infringement occurred. In Sweden, the authority is Integritetsskyddsmyndigheten (IMY). You do not need to contact us before complaining."],
  ]
  return <PublicLayout><section className="mx-auto max-w-3xl space-y-8 px-6 py-14 text-[15px] leading-relaxed">
    <h1 className="text-3xl font-bold">Privacy notice</h1>
    <p>Last updated: September 5, 2026. We will update this notice when processing changes and provide additional notice where required.</p>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Who is responsible</h2>
      <p>{process.env.PRIVACY_CONTROLLER_NAME || "Graduates Corner — legal operator details pending confirmation."}</p>
      <p>{process.env.PRIVACY_CONTROLLER_ADDRESS || "The operator’s postal address must be supplied before production launch."}</p>
      <p>Privacy contact: <a className="underline" href="mailto:admin@graduatescorner.com">admin@graduatescorner.com</a>.</p>
      <Link className="underline" href="/privacy">Download your account data or exercise your rights</Link>
    </section>
    {sections.map(([title, text]) => <section key={title} className="space-y-3"><h2 className="text-xl font-semibold">{title}</h2><p className="text-muted-foreground">{text}</p></section>)}
    <p><a className="underline" href="https://www.imy.se/en/individuals/">Swedish supervisory authority (IMY)</a></p>
  </section></PublicLayout>
}
