import { VERIFIED_THESIS_SOURCES } from "./thesis-sources"

export type EmployerAdapter = "html" | "smartrecruiters" | "workday" | "eightfold" | "successfactors" | "avature" | "deel"
export type EmployerSource = {
  id: string
  name: string
  country: string
  publicUrl: string
  listingUrl?: string
  adapter: EmployerAdapter
  allowedHosts: string[]
  tenant?: string
  board?: string
  verified?: boolean
  note?: string
}

// Employer names and official starting pages supplied by the site operator.
// ATS endpoints are configured only after checking the actual career page.
const rows: [string, string, string, string][] = [
  ["volvo", "Volvo Group", "Sweden", "https://jobs.volvogroup.com/"],
  ["scania", "Scania", "Sweden", "https://www.scania.com/group/en/home/career/students-and-graduates/thesis-projects.html"],
  ["ericsson", "Ericsson", "Sweden", "https://jobs.ericsson.com/careers?query=Master+Thesis"],
  ["saab", "Saab", "Sweden", "https://www.saab.com/career/job-opportunities"],
  ["abb", "ABB", "Sweden", "https://careers.abb/global/en/search-results?keywords=thesis"],
  ["sandvik", "Sandvik", "Sweden", "https://www.sandvik.com/en/careers/"],
  ["skf", "SKF", "Sweden", "https://www.skf.com/group/careers"],
  ["alfa-laval", "Alfa Laval", "Sweden", "https://www.alfalaval.com/about-us/careers/"],
  ["trelleborg", "Trelleborg", "Sweden", "https://www.trelleborg.com/en/careers"],
  ["atlas-copco", "Atlas Copco", "Sweden", "https://www.atlascopcogroup.com/en/careers"],
  ["sweco", "Sweco", "Sweden", "https://www.sweco.se/karriar/"],
  ["epiroc", "Epiroc", "Sweden", "https://www.epirocgroup.com/en/careers"],
  ["hexagon", "Hexagon", "Sweden", "https://hexagon.com/company/careers"],
  ["tetra-pak", "Tetra Pak", "Sweden", "https://www.tetrapak.com/careers"],
  ["boliden", "Boliden", "Sweden", "https://www.boliden.com/careers/"],
  ["seb", "SEB", "Sweden", "https://seb.se/karriar"],
  ["handelsbanken", "Handelsbanken", "Sweden", "https://career.handelsbanken.se/"],
  ["swedbank", "Swedbank", "Sweden", "https://www.swedbank.com/en/about-swedbank/careers.html"],
  ["nordea", "Nordea", "Nordics", "https://www.nordea.com/en/careers"],
  ["lansforsakringar", "Länsförsäkringar", "Sweden", "https://www.lansforsakringar.se/jobb/"],
  ["if", "If Insurance", "Sweden", "https://www.if-insurance.com/careers"],
  ["spotify", "Spotify", "Sweden", "https://www.lifeatspotify.com/"],
  ["klarna", "Klarna", "Sweden", "https://www.klarna.com/careers/"],
  ["hm", "H&M Group", "Sweden", "https://hmgroup.com/careers/"],
  ["ikea", "IKEA", "Sweden", "https://www.ikea.jobs/"],
  ["essity", "Essity", "Sweden", "https://www.essity.com/careers/"],
  ["king", "King", "Sweden", "https://www.king.com/careers/"],
  ["telia", "Telia", "Sweden", "https://www.telia.com/en/careers"],
  ["equinor", "Equinor", "Norway", "https://www.equinor.com/careers/join-equinor/students"],
  ["dnv", "DNV", "Norway", "https://www.dnv.com/careers/"],
  ["kongsberg", "Kongsberg Gruppen", "Norway", "https://www.kongsberg.com/no/career/"],
  ["telenor", "Telenor", "Norway", "https://www.telenor.com/careers/"],
  ["statkraft", "Statkraft", "Norway", "https://www.statkraft.com/careers/"],
  ["hydro", "Norsk Hydro", "Norway", "https://www.hydro.com/careers/"],
  ["aker-bp", "Aker BP", "Norway", "https://akerbp.com/careers/"],
  ["aker-solutions", "Aker Solutions", "Norway", "https://www.akersolutions.com/careers/"],
  ["yara", "Yara International", "Norway", "https://www.yara.com/careers/"],
  ["dnb", "DNB", "Norway", "https://www.dnb.no/karriere"],
  ["storebrand", "Storebrand", "Norway", "https://www.storebrand.no/karriere"],
  ["schibsted", "Schibsted", "Norway", "https://schibsted.com/careers/"],
  ["norwegian", "Norwegian Air Shuttle", "Norway", "https://www.norwegian.com/careers/"],
  ["nokia", "Nokia", "Finland", "https://www.nokia.com/careers/"],
  ["kone", "Kone", "Finland", "https://www.kone.com/careers/"],
  ["wartsila", "Wärtsilä", "Finland", "https://www.wartsila.com/careers"],
  ["neste", "Neste", "Finland", "https://www.neste.com/careers"],
  ["fortum", "Fortum", "Finland", "https://www.fortum.com/careers"],
  ["metso", "Metso", "Finland", "https://www.metso.com/careers/"],
  ["valmet", "Valmet", "Finland", "https://www.valmet.com/careers/"],
  ["upm", "UPM", "Finland", "https://www.upm.com/careers/"],
  ["stora-enso", "Stora Enso", "Finland", "https://www.storaenso.com/en/careers"],
  ["op", "OP Financial Group", "Finland", "https://www.op.fi/careers"],
  ["elisa", "Elisa", "Finland", "https://elisa.com/careers/"],
  ["konecranes", "Konecranes", "Finland", "https://www.konecranes.com/careers"],
  ["outokumpu", "Outokumpu", "Finland", "https://www.outokumpu.com/careers"],
  ["asml", "ASML", "Netherlands", "https://www.asml.com/en/careers/search-jobs"],
  ["philips", "Philips", "Netherlands", "https://www.philips.com/a-w/careers.html"],
  ["shell", "Shell", "Netherlands", "https://www.shell.com/careers.html"],
  ["ing", "ING", "Netherlands", "https://www.ing.jobs/"],
  ["abn-amro", "ABN AMRO", "Netherlands", "https://www.abnamro.com/careers"],
  ["rabobank", "Rabobank", "Netherlands", "https://www.rabobank.jobs/"],
  ["klm", "KLM", "Netherlands", "https://www.werkenbijklm.nl/"],
  ["nxp", "NXP Semiconductors", "Netherlands", "https://www.nxp.com/company/about-nxp/careers"],
  ["tno", "TNO", "Netherlands", "https://www.tno.nl/en/careers/vacancies/"],
  ["unilever", "Unilever", "Netherlands", "https://www.unilever.com/careers/"],
  ["heineken", "Heineken", "Netherlands", "https://www.theheinekencompany.com/careers"],
  ["ahold-delhaize", "Ahold Delhaize", "Netherlands", "https://www.aholddelhaize.com/careers/"],
  ["dsm-firmenich", "DSM-Firmenich", "Netherlands", "https://www.dsm-firmenich.com/careers"],
  ["akzonobel", "AkzoNobel", "Netherlands", "https://www.akzonobel.com/careers"],
  ["booking", "Booking.com", "Netherlands", "https://www.booking.com/careers"],
  ["siemens", "Siemens", "Germany", "https://jobs.siemens.com/careers"],
  ["bosch", "Bosch", "Germany", "https://www.bosch-career.com/"],
  ["volkswagen", "Volkswagen Group", "Germany", "https://www.volkswagenag.com/en/career.html"],
  ["bmw", "BMW Group", "Germany", "https://www.bmwgroup.jobs/"],
  ["mercedes", "Mercedes-Benz", "Germany", "https://www.mercedes-benz-career.com/"],
  ["continental", "Continental", "Germany", "https://www.continental.com/en/career/"],
  ["zf", "ZF Friedrichshafen", "Germany", "https://www.zf.com/careers/"],
  ["siemens-energy", "Siemens Energy", "Germany", "https://www.siemens-energy.com/careers"],
  ["basf", "BASF", "Germany", "https://www.basf.com/careers"],
  ["thyssenkrupp", "Thyssenkrupp", "Germany", "https://www.thyssenkrupp.com/careers"],
  ["sap", "SAP", "Germany", "https://jobs.sap.com/"],
  ["telekom", "Deutsche Telekom", "Germany", "https://www.telekom.com/careers"],
  ["infineon", "Infineon", "Germany", "https://www.infineon.com/careers"],
  ["bayer", "Bayer", "Germany", "https://career.bayer.com/"],
  ["merck", "Merck KGaA", "Germany", "https://www.merckgroup.com/careers"],
  ["boehringer", "Boehringer Ingelheim", "Germany", "https://www.boehringer-ingelheim.com/careers"],
  ["deutsche-bank", "Deutsche Bank", "Germany", "https://careers.db.com/"],
  ["allianz", "Allianz", "Germany", "https://careers.allianz.com/"],
  ["munich-re", "Munich Re", "Germany", "https://www.munichre.com/careers"],
  ["commerzbank", "Commerzbank", "Germany", "https://www.commerzbank.com/careers"],
  ["fraunhofer", "Fraunhofer", "Germany", "https://jobs.fraunhofer.de/"],
  ["dlr", "DLR", "Germany", "https://www.dlr.de/en/careers/vacancies"],
  ["max-planck", "Max Planck Institutes", "Germany", "https://jobs.mpg.de/"],
  ["helmholtz", "Helmholtz Association", "Germany", "https://www.helmholtz.de/en/careers/"],
  ["mckinsey", "McKinsey", "Europe", "https://www.mckinsey.com/careers"],
  ["bcg", "BCG", "Europe", "https://careers.bcg.com/"],
  ["bain", "Bain", "Europe", "https://www.bain.com/careers/"],
  ["deloitte", "Deloitte", "Europe", "https://www.deloitte.com/careers"],
  ["pwc", "PwC", "Europe", "https://www.pwc.com/careers"],
  ["ey", "EY", "Europe", "https://www.ey.com/careers"],
  ["kpmg", "KPMG", "Europe", "https://kpmg.com/careers"],
  ["accenture", "Accenture", "Europe", "https://www.accenture.com/careers"],
]

const endpoints: Record<string, Partial<EmployerSource>> = {
  volvo: { adapter: "successfactors", listingUrl: "https://jobs.volvogroup.com/search/", verified: true },
  scania: { adapter: "successfactors", listingUrl: "https://jobs.scania.com/search/", allowedHosts: ["scania.com"], verified: true },
  ericsson: { adapter: "eightfold", tenant: "ericsson.com", listingUrl: "https://jobs.ericsson.com/careers", verified: true },
  abb: { adapter: "workday", tenant: "abb", board: "External_Career_Page", listingUrl: "https://abb.wd3.myworkdayjobs.com/External_Career_Page", allowedHosts: ["careers.abb", "abb.wd3.myworkdayjobs.com"], verified: true },
  equinor: { adapter: "workday", tenant: "equinor", board: "EQNR", listingUrl: "https://equinor.wd3.myworkdayjobs.com/EQNR", allowedHosts: ["equinor.com", "equinor.wd3.myworkdayjobs.com"], verified: true },
  asml: { listingUrl: "https://www.asml.com/en/careers/find-your-job" },
  sandvik: { adapter: "workday", tenant: "sandvik", board: "sandvik-jobs", listingUrl: "https://sandvik.wd3.myworkdayjobs.com/sandvik-jobs", allowedHosts: ["home.sandvik", "sandvik.wd3.myworkdayjobs.com"], verified: true },
  storebrand: { adapter: "workday", tenant: "storebrand", board: "Storebrand_Careers", listingUrl: "https://storebrand.wd3.myworkdayjobs.com/Storebrand_Careers", allowedHosts: ["storebrand.no", "storebrand.wd3.myworkdayjobs.com"], verified: true },
  kone: { adapter: "workday", tenant: "kone", board: "Careers", listingUrl: "https://kone.wd3.myworkdayjobs.com/Careers", allowedHosts: ["kone.com", "kone.wd3.myworkdayjobs.com"], verified: true },
  valmet: { adapter: "workday", tenant: "valmet", board: "External", listingUrl: "https://valmet.wd103.myworkdayjobs.com/External", allowedHosts: ["valmet.com", "valmet.wd103.myworkdayjobs.com"], verified: true },
  nxp: { adapter: "workday", tenant: "nxp", board: "careers", listingUrl: "https://nxp.wd3.myworkdayjobs.com/careers", allowedHosts: ["nxp.com", "nxp.wd3.myworkdayjobs.com"], verified: true },
  accenture: { adapter: "workday", tenant: "accenture", board: "AccentureCareers", listingUrl: "https://accenture.wd103.myworkdayjobs.com/AccentureCareers", allowedHosts: ["accenture.com", "accenture.wd103.myworkdayjobs.com"], verified: true },
  bosch: { adapter: "smartrecruiters", tenant: "BoschGroup", listingUrl: "https://api.smartrecruiters.com/v1/companies/BoschGroup/postings", allowedHosts: ["bosch-career.com", "api.smartrecruiters.com", "jobs.smartrecruiters.com"], verified: true },
  fraunhofer: { adapter: "successfactors", listingUrl: "https://jobs.fraunhofer.de/search/", verified: true },
  dlr: { adapter: "successfactors", listingUrl: "https://jobs.dlr.de/search/", allowedHosts: ["dlr.de"], verified: true },
  "tetra-pak": { adapter: "successfactors", listingUrl: "https://jobs.tetrapak.com/search/", verified: true },
  hydro: { adapter: "successfactors", listingUrl: "https://jobs.hydro.com/search/", verified: true },
  yara: { adapter: "successfactors", listingUrl: "https://jobs.yara.com/search/", verified: true },
  fortum: { adapter: "successfactors", listingUrl: "https://jobs.fortum.com/search/", verified: true },
  neste: { adapter: "successfactors", listingUrl: "https://jobs.neste.com/search/", verified: true },
  sap: { adapter: "successfactors", listingUrl: "https://jobs.sap.com/search/", verified: true },
  heineken: { adapter: "successfactors", listingUrl: "https://careers.theheinekencompany.com/search/", verified: true },
  tno: { listingUrl: "https://www.tno.nl/en/careers/vacancies/", verified: true },
  saab: { adapter: "workday", tenant: "saabgroup", board: "Saab_careers", listingUrl: "https://saabgroup.wd116.myworkdayjobs.com/Saab_careers", allowedHosts: ["saab.com", "saabgroup.wd116.myworkdayjobs.com"], verified: true },
  essity: { adapter: "workday", tenant: "essity", board: "Job_opportunities", listingUrl: "https://essity.wd3.myworkdayjobs.com/Job_opportunities", allowedHosts: ["essity.com", "essity.wd3.myworkdayjobs.com"], verified: true },
  philips: { adapter: "workday", tenant: "philips", board: "jobs-and-careers", listingUrl: "https://philips.wd3.myworkdayjobs.com/jobs-and-careers", allowedHosts: ["philips.com", "philips.wd3.myworkdayjobs.com"], verified: true },
  wartsila: { adapter: "successfactors", listingUrl: "https://careers.wartsila.com/search/", verified: true },
  kongsberg: { listingUrl: "https://www.kongsberg.com/careers/vacancies/", verified: true },
  spotify: { listingUrl: "https://www.lifeatspotify.com/jobs", verified: true },
  siemens: { adapter: "avature", listingUrl: "https://jobs.siemens.com/en_US/externaljobs/SearchJobs", verified: true },
  dnv: { listingUrl: "https://jobs.dnv.com/job-search", allowedHosts: ["dnv.com"] },
  statkraft: { listingUrl: "https://www.statkraft.com/careers/job-opportunities/" },
  "aker-solutions": { listingUrl: "https://www.akersolutions.com/careers/job-search/" },
  telenor: { listingUrl: "https://www.telenor.com/career/open-positions/" },
  ing: { listingUrl: "https://careers.ing.com/en/search-jobs", allowedHosts: ["ing.com"] },
  "dsm-firmenich": { adapter: "eightfold", tenant: "dsm.com", listingUrl: "https://jobs.dsm-firmenich.com/careers", verified: true },
  infineon: { adapter: "eightfold", tenant: "infineon.com", listingUrl: "https://jobs.infineon.com/careers", verified: true },
  bcg: { adapter: "eightfold", tenant: "bcg.com", listingUrl: "https://bcg.eightfold.ai/careers", allowedHosts: ["bcg.com", "bcg.eightfold.ai"] },
  klarna: { adapter: "deel", listingUrl: "https://jobs.deel.com/klarna", allowedHosts: ["jobs.deel.com"], verified: true },
}

const existingSources: EmployerSource[] = rows.map(([id, name, country, publicUrl]) => ({
  id, name, country, publicUrl, adapter: "html",
  allowedHosts: [new URL(publicUrl).hostname.replace(/^www\./, "")],
  ...endpoints[id],
}))

export const EMPLOYER_SOURCES: EmployerSource[] = [
  ...existingSources.map(source => VERIFIED_THESIS_SOURCES.find(update => update.id === source.id) || source),
  ...VERIFIED_THESIS_SOURCES.filter(source => !existingSources.some(existing => existing.id === source.id)),
]

export function getEmployerSource(id: string) { return EMPLOYER_SOURCES.find(source => source.id === id) }
