export const SEO_LANDINGS = [
  {slug:"phd-positions-germany",title:"PhD positions in Germany",kind:"phd",country:"Germany",intro:"Compare doctoral projects at German universities, research institutes and employers. Check the research topic, supervision and application deadline before preparing your documents.",advice:"Confirm whether funding is an employment contract or a scholarship, and check the duration, working hours and degree requirements in the original posting."},
  {slug:"phd-positions-sweden",title:"PhD positions in Sweden",kind:"phd",country:"Sweden",intro:"Explore doctoral research opportunities in Sweden and compare projects by subject, institution and closing date.",advice:"Match your research interests to the advertised project. Check the institution's requirements for transcripts, degree equivalence, language skills and references."},
  {slug:"phd-positions-netherlands",title:"PhD positions in the Netherlands",kind:"phd",country:"Netherlands",intro:"Find doctoral vacancies from Dutch research organizations and universities, with original application links and visible deadlines.",advice:"Compare the proposed research methods, supervision, contract duration and application documents. Use the official vacancy as the final source of requirements."},
  {slug:"phd-positions-norway",title:"PhD positions in Norway",kind:"phd",country:"Norway",intro:"Browse current doctoral opportunities in Norway, from engineering and technology to natural and social sciences.",advice:"Read the project scope and admission requirements together. Some vacancies request a project proposal; others recruit for an already defined research project."},
  {slug:"phd-positions-finland",title:"PhD positions in Finland",kind:"phd",country:"Finland",intro:"Discover doctoral research positions in Finland and compare the university, project, location and application deadline.",advice:"Check whether applying for the position and obtaining doctoral study rights are separate steps. Follow the process described by the advertising institution."},
  {slug:"funded-master-thesis-sweden",title:"Funded master's thesis opportunities in Sweden",kind:"master",country:"Sweden",funded:true,intro:"Find Swedish master's thesis projects explicitly listed as paid or offering a stipend. These funding labels do not imply a particular amount or employment contract.",advice:"Confirm payment conditions, academic supervision, intellectual property arrangements and university approval before accepting an industry thesis project."},
  {slug:"internships-netherlands",title:"Internships in the Netherlands",kind:"master",country:"Netherlands",internship:true,intro:"Browse internship placements in the Netherlands and compare the organization, subject and application deadline.",advice:"Check student-enrollment requirements, expected availability, compensation and whether the internship can count toward your degree."},
  {slug:"graduate-trainee-programs-europe",title:"Graduate trainee programs in Europe",kind:"trainee",country:"Europe",intro:"Compare structured graduate programs across European countries, including rotations, training and early-career placements.",advice:"Check graduation-date eligibility, language requirements, location changes during rotations and the employer's selection stages."},
  {slug:"phd-artificial-intelligence",title:"PhD positions in artificial intelligence",kind:"phd",field:"artificial intelligence|machine learning|deep learning|computer vision",intro:"Explore doctoral projects involving artificial intelligence, machine learning and computer vision across research institutions.",advice:"Compare the methodological focus and prerequisites. Prepare evidence of relevant mathematical, programming and research experience rather than sending a generic application."},
  {slug:"phd-engineering",title:"PhD positions in engineering",kind:"phd",field:"engineering|robotics|electrical|mechanical",intro:"Find engineering PhD projects covering applied research, systems, materials and technology development.",advice:"Look for the research question, experimental or computational methods, facilities and collaboration partners described in each project."},
] as const
export type SeoLanding = (typeof SEO_LANDINGS)[number]
