import assert from 'node:assert/strict'
import { typescriptLoader } from './employer-test-loader.mjs'
const base=typescriptLoader()
const load=typescriptLoader({'@/lib/text':base('lib/text.ts')})
const {opportunityId,opportunityPath}=load('lib/opportunity-url.ts')
const {seoCountry}=load('lib/seo-location.ts')
const {buildJobPostingSchema,createPageMetadata}=load('lib/seo.ts')
const id='11111111-1111-4111-8111-111111111111'
const path=opportunityPath('phd',id,'PhD in Machine Learning','TU Delft')
assert.equal(opportunityId(path.split('/').at(-1)),id)
assert.equal(opportunityId(id),id)
assert.equal(opportunityId('not-a-job'),null)
assert.ok(path.startsWith('/phd-positions/phd-in-machine-learning-tu-delft--'))
assert.equal(seoCountry('Göteborg').code,'SE')
assert.equal(seoCountry('Södertälje, SE, 151 38').code,'SE')
assert.equal(seoCountry('Eindhoven; Netherlands').code,'NL')
assert.equal(seoCountry('Cambridge'),null,'Ambiguous city must not invent a country')
assert.equal(seoCountry('Location not specified'),null)
assert.equal(seoCountry('Sweden; Germany'),null)
const input={id,title:'AI research position',description:'Research neural network systems with an academic team.',organization:'Test University',location:'Delft, Netherlands',deadline:'2099-12-31',createdAt:'2026-01-01',path,field:'AI',kind:'phd'}
const job=buildJobPostingSchema(input)
assert.equal(job['@type'],'JobPosting')
assert.equal(job.jobLocation.address.addressCountry,'NL')
assert.equal(job.employmentType,undefined,'Do not infer full time from PhD')
assert.equal(buildJobPostingSchema({...input,kind:'trainee'}).employmentType,undefined,'Trainee programs are not automatically internships')
assert.equal(buildJobPostingSchema({...input,kind:'internship'}).employmentType,'INTERN')
assert.equal(buildJobPostingSchema({...input,deadline:'2000-01-01'}),null)
assert.equal(buildJobPostingSchema({...input,location:'Worldwide'}),null)
assert.ok(!('jobLocationType' in buildJobPostingSchema({...input,location:'Hybrid, Delft, Netherlands'})))
assert.equal(createPageMetadata({title:'AI research',description:'A'.repeat(500),path}).alternates.canonical,'https://graduatescorner.com'+path)
assert.ok(createPageMetadata({title:'AI research',description:'A'.repeat(500),path}).description.length<=161)
console.log('PASS SEO canonical URLs, legacy IDs, country validation, accurate job types, expired schema and metadata')
const {sanitizeListingHtml}=load('lib/sanitize-listing-html.ts')
const clean=sanitizeListingHtml('<h1>Research</h1><p onclick="alert(1)">Visible description</p><script>alert(1)</script><a href="javascript:alert(1)">Unsafe</a><a href="https://example.com/apply">Apply</a><svg><script>alert(2)</script></svg>')
assert.ok(clean.includes('<h3>Research</h3>') && clean.includes('Visible description'))
assert.ok(!/<script|onclick|javascript|<svg|<h1/i.test(clean))
assert.ok(clean.includes('href="https://example.com/apply"'))
console.log('PASS server description sanitization and safe application links')
